kpi/kpi/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view


urlpatterns = [
    path(f'{settings.ADMIN_PATH}/', admin.site.urls),
    # path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # path('schema/', get_schema_view(title=API_TITLE)),
]

if 'detection_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('detection_management.urls',
                        namespace='detection')),

if 'visiting_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('visiting_management.urls',
                        namespace='visiting')),

if 'public_engagement_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('public_engagement_management.urls',
                        namespace='public_engagement')),

if 'template' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('template.urls', namespace='template')),

if 'unical_accounts' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('unical_accounts.urls',
                        namespace='unical_accounts')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    from djangosaml2 import views as saml2_views

    import saml2_sp.urls

    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

    urlpatterns += path('{}/login/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LoginView.as_view(), name='login'),
    urlpatterns += path('{}/acs/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.AssertionConsumerServiceView.as_view(), name='saml2_acs'),
    urlpatterns += path('{}/logout/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutInitView.as_view(), name='logout'),
    urlpatterns += path('{}/ls/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls'),
    urlpatterns += path('{}/ls/post/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls_post'),
    urlpatterns += path('{}/metadata/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.MetadataView.as_view(), name='saml2_metadata'),
else:
    urlpatterns += path('{}/login/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LoginView.as_view(
                            template_name='login.html'),
                        name='login'),
    urlpatterns += path('{}/logout/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LogoutView.as_view(
                            template_name='logout.html', next_page='/'),
                        name='logout'),

kpi/public_engagement_monitoring/urls.py
from django.urls import path

from . api.views import (generic as api_generic,
                         user as api_user,
                         operator as api_evaluation_operator,
                         patronage as api_patronage_operator,
                         manager as api_manager,
                         involved_personnel as api_involved_personnel,
                         involved_structures as api_involved_structures)

from . views import (generic,
                     involved_personnel,
                     involved_structures,
                     manager,
                     operator,
                     patronage,
                     user)


app_name = 'public_engagement_monitoring'


# app prefix
prefix = 'public-engagement-monitoring'

api_prefix = "api"
user_prefix = 'user'
involved_personnel_prefix = 'involved-personnel'
involved_structures_prefix = 'involved-structures'
operator_prefix = 'operator'
validator_prefix = 'evaluation'
patronage_prefix = 'patronage'
manager_prefix = 'manager'

urlpatterns = [
    path(f'{prefix}/', generic.dashboard, name='dashboard'),
    path(f'{prefix}/events/<int:event_id>/poster/download/', generic.download_event_poster, name='download_event_poster'),

    # user
    path(f'{prefix}/{user_prefix}/events/', user.events, name='user_events'),
    path(f'{prefix}/{user_prefix}/events/new/',
         user.new_event_choose_referent, name='user_new_event_choose_referent'),
    path(f'{prefix}/{user_prefix}/events/new/basic-info/',
         user.new_event_basic_info, name='user_new_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/',
         user.event, name='user_event'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/basic-info/',
         user.event_basic_info, name='user_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/data/',
         user.event_data, name='user_event_data'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/report/',
         user.event_report, name='user_event_report'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/',
         user.event_people, name='user_event_people'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/delete/<int:person_id>/',
         user.event_people_delete, name='user_event_people_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/',
         user.event_structures, name='user_event_structures'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/delete/<int:structure_id>/',
         user.event_structures_delete, name='user_event_structures_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation/',
         user.event_request_evaluation, name='user_event_request_evaluation'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation-cancel/',
         user.event_request_evaluation_cancel, name='user_event_request_evaluation_cancel'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/clone/',
         user.event_clone, name='user_event_clone'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/delete/',
         user.event_delete, name='user_event_delete'),

    # evaluation operator
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/',
         operator.dashboard, name='operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/',
         operator.events, name='operator_events'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/',
         operator.event, name='operator_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         operator.take_event, name='operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         operator.event_basic_info, name='operator_event_basic_info'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         operator.event_data, name='operator_event_data'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         operator.event_people, name='operator_event_people'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         operator.event_people_delete, name='operator_event_people_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         operator.event_structures, name='operator_event_structures'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         operator.event_structures_delete, name='operator_event_structures_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         operator.event_evaluation, name='operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         operator.event_reopen_evaluation, name='operator_event_reopen_evaluation'),

    # patronage operator
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/',
         patronage.dashboard, name='patronage_operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/',
         patronage.events, name='patronage_operator_events'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/',
         patronage.event, name='patronage_operator_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         patronage.take_event, name='patronage_operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         patronage.event_evaluation, name='patronage_operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         patronage.event_reopen_evaluation, name='patronage_operator_event_reopen_evaluation'),

    # involved structures
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/',
         involved_structures.dashboard, name='involved_structures_dashboard'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/',
        involved_structures.events, name='involved_structures_events'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/<int:event_id>/',
        involved_structures.event, name='involved_structures_event'),

    # manager
    path(f'{prefix}/{manager_prefix}/',
         manager.dashboard, name='manager_dashboard'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/',
         manager.events, name='manager_events'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/',
         manager.new_event_choose_referent, name='manager_new_event_choose_referent'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/basic-info/',
         manager.new_event_basic_info, name='manager_new_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/',
         manager.event, name='manager_event'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         manager.event_basic_info, name='manager_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         manager.event_data, name='manager_event_data'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         manager.event_people, name='manager_event_people'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         manager.event_people_delete, name='manager_event_people_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         manager.event_structures, name='manager_event_structures'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         manager.event_structures_delete, name='manager_event_structures_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/report/',
         manager.event_report, name='manager_event_report'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/change-status/',
         manager.event_enable_disable, name='manager_event_enable_disable'),

    # involved personnel
    path(f'{prefix}/{involved_personnel_prefix}/events/', involved_personnel.events, name='involved_personnel_events'),
    path(f'{prefix}/{involved_personnel_prefix}/events/<int:event_id>/',
         involved_personnel.event, name='involved_personnel_event'),

    # API
    path(f'{prefix}/{api_prefix}/structures/', api_generic.OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/{api_prefix}/events/',
         api_generic.PublicEngagementApprovedEventList.as_view(), name='api_generic_approved_events'),
    path(f'{prefix}/{api_prefix}/events/<int:pk>/',
         api_generic.PublicEngagementApprovedEventDetail.as_view(), name='api_generic_approved_event'),
    path(f'{prefix}/{api_prefix}/{user_prefix}/events/',
         api_user.PublicEngagementEventList.as_view(), name='api_user_events'),
    path(f'{prefix}/{api_prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/',

kpi/template/urls.py
from django.urls import path
from .views import dashboard

app_name = 'template'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

kpi/unical_accounts/urls.py
from django.urls import path

from . datatables import *
from .views import *

app_name = "unical_accounts"

prefix = 'users'

urlpatterns = [

    # url(r'^login/$', Login, name='login'),
    # path('logout', Logout, name='logout'),

    path(f'{prefix}/users.json', datatables_users, name='users_json'),
    path(f'{prefix}/', users, name='users'),
    path(f'{prefix}/new/', new_user, name='users-new'),
    path(f'{prefix}/<str:user_tax_code>/edit/', edit_user, name='users-edit'),

    path('account/', account, name='account'),
    path('account/edit/', changeData, name='change_data'),
    path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),

]

kpi/visiting_management/urls.py
from django.urls import path

from . api.views import *
from . datatables import *
from . views import *


app_name = 'visiting'


# app prefix
prefix = 'visiting'

urlpatterns = [

    path(f'{prefix}/', dashboard, name='dashboard'),
    path(f'{prefix}/api/structures/', OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/api/structures/<int:pk>/', OrganizationalStructureDetail.as_view(), name='api_structure'),
    path(f'{prefix}/api/users/', VisitingUserList.as_view(), name='api_users'),
    path(f'{prefix}/api/users/<int:pk>/', VisitingUserDetail.as_view(), name='api_user'),

    # datatables
    path(f'{prefix}/<str:structure_slug>/visitings.json',
         datatables_structure_visitings, name='structure_visitings_json'),

    path(f'{prefix}/<str:structure_slug>/',
         structure_visitings, name='structure_visitings'),
    path(f'{prefix}/<str:structure_slug>/new/',
         new_structure_visiting, name='new_structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/',
         structure_visiting, name='structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/edit/',
         edit_structure_visiting, name='edit_structure_visiting'),
]

kpi/public_engagement_monitoring/api/views/generic.py
from django_filters.rest_framework import *

from organizational_area.api.views import *

from rest_framework import filters, generics, permissions

from template.api.pagination import KpiPagination

from ... utils import *
from .. filters import PublicEngagementEventFilter
from .. serializers import *


class PublicEngagementEventList(generics.ListAPIView):

    permission_classes = [permissions.IsAuthenticated]
    serializer_class = PublicEngagementEventSerializer
    filter_backends = [DjangoFilterBackend,
                       filters.SearchFilter,
                       filters.OrderingFilter]
    filterset_class =  PublicEngagementEventFilter
    search_fields = ['title', 'referent__last_name', 'structure__name']
    pagination_class = KpiPagination
    ordering_fields = ['start', 'end', 'title', 'referent__last_name']
    ordering = ['-start']


class PublicEngagementApprovedEventList(PublicEngagementEventList):
    serializer_class = PublicEngagementEventLiteSerializer

    def get_queryset(self, **kwargs):
        """
        """
        events = PublicEngagementEvent.objects\
            .prefetch_related('data', 'report')\
            .select_related('referent', 'structure')\
            .filter(structure__is_active=True,
                    operator_evaluation_success=True)

        return events


class PublicEngagementApprovedEventDetail(generics.RetrieveAPIView):
    serializer_class = PublicEngagementEventLiteSerializer
    queryset = PublicEngagementEvent.objects.all()


class OrganizationalStructureList(OrganizationalStructureList):
    permission_classes = [permissions.IsAuthenticated]
    queryset = OrganizationalStructure.objects.filter(is_active=True,
                                                      is_public_engagement_enabled=True,
                                                      is_internal=True,)

kpi/public_engagement_monitoring/api/views/involved_personnel.py
from django.db.models import Q


from rest_framework import permissions

from ... models import PublicEngagementEvent

# from .. permissions import *

from . generic import PublicEngagementEventList


class PublicEngagementEventList(PublicEngagementEventList):

    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self, **kwargs):
        """
        """
        events = PublicEngagementEvent.objects\
            .prefetch_related('data', 'report')\
            .select_related('referent', 'structure')\
            .filter(data__involved_personnel=self.request.user,
                    structure__is_active=True,
                    # ~ is_active=True,
                    operator_evaluation_date__isnull=False)
                    # ~ operator_evaluation_success=True)
        return events

kpi/public_engagement_monitoring/templates/pem/operator/dashboard.html
{% extends 'pem/base.html' %}

{% load i18n %}
{% load static %}
{% load public_engagement_monitoring_tags %}


{% block top_content %}
<h2>{% trans "Structures" %}</h2>
<p>{% trans "Choose the structure to manage" %}</p>
<small>{% trans "The counters only take charge of the events for which the monitoring year is still active" %}.</small>
{% endblock top_content %}

{% block clean_content %}
<div class="row mt-5">
    {% for structure in structures %}
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ structure }}
                    </h5>
                    <hr>
                    <p>
                        <b>{% trans "To be handled" %}:</b>
                        {% filter_events_per_structure_id event_counts structure.pk as structure_events %}
                        {% if structure_events.0.to_handle_count  %}
                        <span class="badge bg-info">{{ structure_events.0.to_handle_count }}</span>
                        {% else %}
                        0
                        {% endif %}
                        <br>
                        <b>{% trans "To evaluate" %}:</b>
                        {% if structure_events.0.to_evaluate_count %}
                        <span class="badge bg-warning">{{ structure_events.0.to_evaluate_count }}</span>
                        {% else %}
                        0
                        {% endif %}
                    </p>
                    <a class="read-more" href="{% url 'public_engagement_monitoring:operator_events' structure_slug=structure.slug %}">
                        <span class="text text-primary">{% trans "Manage" %}</span>
                        <svg class="icon">
                            <use href="{% static 'svg/sprites.svg' %}#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    {% endfor %}
</div>
{% endblock clean_content %}

kpi/public_engagement_monitoring/templates/pem/operator/event.html
{% extends 'pem/event.html' %}

{% load i18n %}
{% load static %}

{% load public_engagement_monitoring_tags %}


{% block alerts %}
{{ block.super }}

{% comment %}
{% if event.data and not event.data.involved_personnel.all %}
<div class="alert alert-danger" role="alert">
    {% trans "Other involved personnel missing" %}
</div>
{% endcomment %}
{% if not event.to_evaluate %}
<div class="alert alert-danger" role="alert">
    {% trans "Evaluation request not sent" %}
</div>
{% endif %}
{% endblock alerts %}

{% block actions %}
<div class="text-end mt-5">
{% if event.can_be_handled_for_evaluation %}
<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#take_event">
    <svg class="icon icon-sm icon-white">
        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check"></use>
    </svg> {% trans "Handle" %}
</button>
<div class="it-example-modal d-inline">
   <div class="modal" tabindex="-1" role="dialog" id="take_event" aria-labelledby="take_event-Title">
      <div class="modal-dialog" role="document">
         <div class="modal-content">
            <div class="modal-header">
               <h2 class="modal-title h5" id="take_event-Title">{% trans "Confirm" %}</h2>
               <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Chiudi finestra modale">
                  <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
               </button>
            </div>
            <div class="modal-body">
               <p>{% trans "Do you want to proceed?" %}</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'public_engagement_monitoring:operator_take_event' structure_slug=structure_slug event_id=event.pk %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-success" type="submit">
                        {% trans 'Yes, proceed' %}
                    </button>
                </form>
            </div>
         </div>
      </div>
   </div>
</div>
{% else %}

    {% if event.is_editable_by_operator %}
    <a class="btn btn-outline-secondary" href="{% url 'public_engagement_monitoring:operator_event_basic_info' structure_slug=structure_slug event_id=event.pk %}">
        <svg class="icon icon-sm icon-info">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
        </svg> {% trans "General informations" %}
    </a>
    <a class="btn btn-{% if event.data %}outline-secondary{% else %}success{% endif %}" href="{% url 'public_engagement_monitoring:operator_event_data' structure_slug=structure_slug event_id=event.pk %}">
        <svg class="icon icon-sm icon-{% if event.data %}info{% else %}white{% endif %}">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-{% if event.data %}pencil{% else %}plus-circle{% endif %}"></use>
        </svg> {% trans "Event data" %}
    </a>
    {% endif %}

    {% if event.data and event.is_editable_by_operator %}
    <a class="btn btn-outline-secondary" href="{% url 'public_engagement_monitoring:operator_event_people' structure_slug=structure_slug event_id=event.pk %}">
        <svg class="icon icon-sm icon-info">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
        </svg> {% trans "Other involved personnel" %}
    </a>
    <a class="btn btn-outline-secondary" href="{% url 'public_engagement_monitoring:operator_event_structures' structure_slug=structure_slug event_id=event.pk %}">
        <svg class="icon icon-sm icon-info">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
        </svg> {% trans "Other involved structures" %}
    </a>
    {% endif %}

    {% if event.is_ready_for_evaluation %}
    <a class="btn btn-success" href="{% url 'public_engagement_monitoring:operator_event_evaluation' structure_slug=structure_slug event_id=event.pk %}">
        <svg class="icon icon-sm icon-white">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-check"></use>
        </svg> {% trans "Evaluate" %}
    </a>
    {% elif event.evaluation_can_be_reviewed %}
    <button type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#reopen_evaluation">
        <svg class="icon icon-sm icon-white">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-refresh"></use>
        </svg> {% trans "Reopen evaluation" %}
    </button>
    <div class="it-example-modal d-inline">
       <div class="modal" tabindex="-1" role="dialog" id="reopen_evaluation" aria-labelledby="reopen_evaluation-Title">
          <div class="modal-dialog" role="document">
             <div class="modal-content">
                <div class="modal-header">
                   <h2 class="modal-title h5 " id="reopen_evaluation-Title">{% trans "Confirm" %}</h2>
                   <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Chiudi finestra modale">
                      <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
                   </button>
                </div>
                <div class="modal-body">
                   <p>{% trans "Do you want to reopen the evaluation?" %}</p>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'public_engagement_monitoring:operator_event_reopen_evaluation' structure_slug=structure_slug event_id=event.pk %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-warning" type="submit">
                            {% trans 'Yes, proceed' %}
                        </button>
                    </form>
                </div>
             </div>
          </div>
       </div>
    </div>
    {% endif %}

{% endif %}
</div>
{% endblock actions %}

{% block people %}
{% if event.data.involved_personnel.all %}
<div class="mt-5 h5"><b>{% trans "Other involved personnel" %}</b></div>
<hr />
<div class="table-responsive">
    <table class="table table-hover table-striped">
        {% for person in event.data.involved_personnel.all %}
        <tr>
            <td>{{ person }}</td>
            <td class="text-end">
                {% if event.is_editable_by_operator %}
                <button type="button" class="btn btn-xs btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{ person.pk }}">
                    <svg class="icon icon-sm icon-white">
                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-delete"></use>
                    </svg>
                </button>
                <div class="it-example-modal d-inline">
                   <div class="modal" tabindex="-1" role="dialog" id="delete-{{ person.pk }}" aria-labelledby="delete-{{ person.pk }}-Title">
                      <div class="modal-dialog" role="document">
                         <div class="modal-content">
                            <div class="modal-header">
                               <h2 class="modal-title h5 " id="delete-{{ person.pk }}-Title">{% trans "Confirm" %}</h2>
                               <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Chiudi finestra modale">
                                  <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
                               </button>
                            </div>
                            <div class="modal-body">
                               <p>{% trans "Do you want to confirm the entered data?" %}</p>
                            </div>
                            <div class="modal-footer">
                                <form action="{% url 'public_engagement_monitoring:operator_event_people_delete' structure_slug=structure_slug event_id=event.pk person_id=person.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit">
                                        {% trans 'Yes, proceed' %}
                                    </button>
                                </form>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% endblock people %}

{% block structures %}
{% if event.data.involved_structure.all %}
<div class="mt-5 h5"><b>{% trans "Other involved structures" %}</b></div>
<hr />
<div class="table-responsive">
    <table class="table table-hover table-striped">
        {% for structure in event.data.involved_structure.all %}
        <tr>
            <td>{{ structure }}</td>
            <td class="text-end">
                {% if event.is_editable_by_operator %}
                <button type="button" class="btn btn-xs btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{ structure.pk }}">
                    <svg class="icon icon-sm icon-white">
                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-delete"></use>
                    </svg>
                </button>
                <div class="it-example-modal d-inline">
                   <div class="modal" tabindex="-1" role="dialog" id="delete-{{ structure.pk }}" aria-labelledby="delete-{{ structure.pk }}-Title">
                      <div class="modal-dialog" role="document">
                         <div class="modal-content">
                            <div class="modal-header">
                               <h2 class="modal-title h5 " id="delete-{{ structure.pk }}-Title">{% trans "Confirm" %}</h2>
                               <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Chiudi finestra modale">
                                  <svg class="icon"><use href="{% static 'svg/sprites.svg' %}#it-close"></use></svg>
                               </button>
                            </div>
                            <div class="modal-body">
                               <p>{% trans "Do you want to confirm the entered data?" %}</p>
                            </div>
                            <div class="modal-footer">
                                <form action="{% url 'public_engagement_monitoring:operator_event_structures_delete' structure_slug=structure_slug event_id=event.pk structure_id=structure.pk %}" method="post">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit">
                                        {% trans 'Yes, proceed' %}
                                    </button>
                                </form>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% endblock structures %}