kpi/kpi/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view


urlpatterns = [
    path(f'{settings.ADMIN_PATH}/', admin.site.urls),
    # path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # path('schema/', get_schema_view(title=API_TITLE)),
]

if 'detection_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('detection_management.urls',
                        namespace='detection')),

if 'visiting_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('visiting_management.urls',
                        namespace='visiting')),

if 'public_engagement_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('public_engagement_management.urls',
                        namespace='public_engagement')),

if 'template' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('template.urls', namespace='template')),

if 'unical_accounts' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('unical_accounts.urls',
                        namespace='unical_accounts')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    from djangosaml2 import views as saml2_views

    import saml2_sp.urls

    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

    urlpatterns += path('{}/login/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LoginView.as_view(), name='login'),
    urlpatterns += path('{}/acs/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.AssertionConsumerServiceView.as_view(), name='saml2_acs'),
    urlpatterns += path('{}/logout/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutInitView.as_view(), name='logout'),
    urlpatterns += path('{}/ls/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls'),
    urlpatterns += path('{}/ls/post/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls_post'),
    urlpatterns += path('{}/metadata/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.MetadataView.as_view(), name='saml2_metadata'),
else:
    urlpatterns += path('{}/login/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LoginView.as_view(
                            template_name='login.html'),
                        name='login'),
    urlpatterns += path('{}/logout/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LogoutView.as_view(
                            template_name='logout.html', next_page='/'),
                        name='logout'),

kpi/template/urls.py
from django.urls import path
from .views import dashboard

app_name = 'template'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

kpi/unical_accounts/urls.py
from django.urls import path

from . datatables import *
from .views import *

app_name = "unical_accounts"

prefix = 'users'

urlpatterns = [

    # url(r'^login/$', Login, name='login'),
    # path('logout', Logout, name='logout'),

    path(f'{prefix}/users.json', datatables_users, name='users_json'),
    path(f'{prefix}/', users, name='users'),
    path(f'{prefix}/new/', new_user, name='users-new'),
    path(f'{prefix}/<str:user_tax_code>/edit/', edit_user, name='users-edit'),

    path('account/', account, name='account'),
    path('account/edit/', changeData, name='change_data'),
    path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),

]

kpi/visiting_management/urls.py
from django.urls import path

from . api.views import *
from . datatables import *
from . views import *


app_name = 'visiting'


# app prefix
prefix = 'visiting'

urlpatterns = [

    path(f'{prefix}/', dashboard, name='dashboard'),
    path(f'{prefix}/api/structures/', OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/api/structures/<int:pk>/', OrganizationalStructureDetail.as_view(), name='api_structure'),
    path(f'{prefix}/api/users/', VisitingUserList.as_view(), name='api_users'),
    path(f'{prefix}/api/users/<int:pk>/', VisitingUserDetail.as_view(), name='api_user'),

    # datatables
    path(f'{prefix}/<str:structure_slug>/visitings.json',
         datatables_structure_visitings, name='structure_visitings_json'),

    path(f'{prefix}/<str:structure_slug>/',
         structure_visitings, name='structure_visitings'),
    path(f'{prefix}/<str:structure_slug>/new/',
         new_structure_visiting, name='new_structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/',
         structure_visiting, name='structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/edit/',
         edit_structure_visiting, name='edit_structure_visiting'),
]

kpi/public_engagement_monitoring/api/views/user.py
from django.db.models import Q


from rest_framework import permissions

from ... models import PublicEngagementEvent

# from .. permissions import *

from . generic import PublicEngagementEventList


class PublicEngagementEventList(PublicEngagementEventList):

    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self, **kwargs):
        """
        """
        events = PublicEngagementEvent.objects\
            .prefetch_related('data', 'report')\
            .select_related('referent', 'structure')\
            .filter(Q(referent=self.request.user) |
                    Q(created_by=self.request.user),
                    structure__is_active=True)

        status = self.request.query_params.get('status')
        if status=='approved':
            events = events.filter(operator_evaluation_success=True,
                                   operator_evaluation_date__isnull=False)
        elif status=='rejected':
            events = events.filter(operator_evaluation_success=False,
                                   operator_evaluation_date__isnull=False)

        not_eligible = self.request.query_params.get('not_eligible')
        if not_eligible=='true':
            events = events.filter(is_active=False)

        return events

kpi/public_engagement_monitoring/views/user.py
import requests

from copy import deepcopy

from django.conf import settings
from django.contrib import messages
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.admin.utils import _get_changed_field_labels_from_form
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

from organizational_area.models import *
from organizational_area.utils import user_in_office

from template.utils import *

from .. decorators.generic import *
from .. decorators.user import *
from .. forms import *
from .. models import *
from .. settings import *
from .. utils import *


@login_required
@can_manage_public_engagement
def events(request):
    template = 'pem/user/events.html'
    breadcrumbs = {reverse('template:dashboard'): _('Dashboard'),
                   reverse('public_engagement_monitoring:dashboard'): _('Public engagement'),
                   '#': _('Events')}
    api_url = reverse('public_engagement_monitoring:api_user_events')
    return render(request, template, {'breadcrumbs': breadcrumbs,
                                      'api_url': api_url})


@login_required
def new_event_choose_referent(request):
    request.session.pop('referent', None)
    template = 'pem/event_new.html'
    breadcrumbs = {reverse('template:dashboard'): _('Dashboard'),
                   reverse('public_engagement_monitoring:dashboard'): _('Public engagement'),
                   reverse('public_engagement_monitoring:user_events'): _('Events'),
                   '#': _('New')}

    if request.method == 'POST':
        user_is_referent = request.POST['user_is_referent']
        user_is_referent = True if user_is_referent == 'true' else False

        # se è il referente ma non è un docente
        # if user_is_referent and not user_is_teacher(matricola=request.user.matricola_dipendente):

        # se il referente non ha una matricola da dipendente
        if user_is_referent and not request.user.matricola_dipendente:
            messages.add_message(request, messages.ERROR, _("You cannot enter an event as a referent"))
            return redirect('public_engagement_monitoring:user_new_event_choose_referent')

        # recupero della matricola da dipendente
        # se il referente sono io, la matricola ce l'ho già
        if user_is_referent:
            referent_id = request.user.matricola_dipendente
        # se il referente non sono io, recupero la matricola in chiaro
        else:
            referent_id = requests.post('{}/'.format(API_DECRYPTED_ID),
                                        data={'id': request.POST['referent_id']},
                                        headers={'Authorization': 'Token {}'.format(settings.STORAGE_TOKEN)})
            if referent_id.status_code != 200:
                messages.add_message(request, messages.ERROR, _("Access denied"))
                return redirect('public_engagement_monitoring:user_new_event_choose_referent')

            # matricola in chiaro
            referent_id = referent_id.json()

        # recupero dati completi del referente (in entrambi i casi)
        # es: genere
        response = requests.get('{}{}/'.format(API_ADDRESSBOOK_FULL, referent_id.zfill(6)),
                                headers={'Authorization': 'Token {}'.format(settings.STORAGE_TOKEN)})
        if response.status_code != 200:
            messages.add_message(request, messages.ERROR, _("Unable to retrieve user data from our systems"))
            return redirect('public_engagement_monitoring:user_new_event_choose_referent')

        referent_data = response.json()['results']

        # se sono io il referente
        if user_is_referent:
            referent_user = request.user
        # creo o recupero l'utente dal db locale
        else:
            # controllo se esiste già (i dati locali potrebbero differire da quelli presenti nelle API)
            referent_user = get_user_model().objects.filter(
                codice_fiscale=referent_data['Taxpayer_ID']).first()
            # se l'utente è stato disattivato
            if referent_user and not referent_user.is_active:
                messages.add_message(request, messages.ERROR, _("User deactivated"))
                return redirect('public_engagement_monitoring:user_new_event_choose_referent')
            # se non esiste localmente lo creo
            if not referent_user:
                referent_user = get_user_model().objects.create(username=referent_data['Taxpayer_ID'],
                                                                matricola_dipendente=referent_data['ID'],
                                                                first_name=referent_data['Name'],
                                                                last_name=referent_data['Surname'],
                                                                codice_fiscale=referent_data['Taxpayer_ID'],
                                                                email=next(iter(referent_data['Email']), None),
                                                                gender=referent_data['Gender'])

        # aggiorno il dato sul genere con quello più aggiornato, sempre
        referent_user.gender = referent_data['Gender']
        referent_user.save(update_fields=['gender'])

        # salviamo il referente corrente in sessione
        request.session['referent'] = referent_user.pk
        return redirect('public_engagement_monitoring:user_new_event_basic_info')

    return render(request, template, {'breadcrumbs': breadcrumbs, 'compiled_by_user': True})


@login_required
@can_manage_public_engagement
def new_event_basic_info(request):
    # se non è stato scelto il referente nella fase iniziale
    if not request.session.get('referent'):
        messages.add_message(request, messages.ERROR, _("Event referent is mandatory"))
        return redirect('public_engagement_monitoring:user_new_event_choose_referent')

    template = 'pem/event_basic_info.html'
    form = PublicEngagementEventForm(request=request)

    breadcrumbs = {reverse('template:dashboard'): _('Dashboard'),
                   reverse('public_engagement_monitoring:dashboard'): _('Public engagement'),
                   reverse('public_engagement_monitoring:user_events'): _('Events'),
                   reverse('public_engagement_monitoring:user_new_event_choose_referent'): _('New'),
                   '#': _('General informations'),}

    # post
    if request.method == 'POST':
        form = PublicEngagementEventForm(request=request, data=request.POST)
        if form.is_valid():

            year = form.cleaned_data['start'].year
            # check sull'anno di inizio dell'evento
            if not PublicEngagementAnnualMonitoring.year_is_active(year):
                messages.add_message(
                    request, messages.ERROR, "<b>{}</b>: {} {} {}".format(
                        _('Alert'), _('Monitoring activity year'), year, _('has been disabled')))
            else:
                event = form.save(commit=False)
                event.created_by = request.user
                event.modified_by = request.user
                event.referent = get_user_model().objects.get(
                    pk=request.session.get('referent'))
                event.save()

                log_action(user=request.user,
                           obj=event,
                           flag=ADDITION,
                           msg='[Referente/Delegato] Iniziativa creata')

                messages.add_message(
                    request, messages.SUCCESS, _("First step completed successfully. Now proceed to enter the data"))
                # elimino dalla sessione il referente scelto all'inizio
                request.session.pop('referent', None)
                return redirect('public_engagement_monitoring:user_event',
                                event_id=event.pk)
        else:  # pragma: no cover
            messages.add_message(request, messages.ERROR,
                                 "<b>{}</b>: {}".format(_('Alert'), _('the errors in the form below need to be fixed')))
    return render(request, template, {'breadcrumbs': breadcrumbs, 'form': form})


@login_required
@has_access_to_my_event
def event(request, event_id, event=None):
    template = 'pem/user/event.html'
    breadcrumbs = {reverse('template:dashboard'): _('Dashboard'),
                   reverse('public_engagement_monitoring:dashboard'): _('Public engagement'),
                   reverse('public_engagement_monitoring:user_events'): _('Events'),
                   '#': event.title}

    logs = LogEntry.objects.filter(content_type_id=ContentType.objects.get_for_model(event).pk,
                                   object_id=event.pk)

    return render(request, template, {'breadcrumbs': breadcrumbs,
                                      'event': event,
                                      'logs': logs})


@login_required
@has_access_to_my_event
def event_basic_info(request, event_id, event=None):
    template = 'pem/event_basic_info.html'
    breadcrumbs = {reverse('template:dashboard'): _('Dashboard'),
                   reverse('public_engagement_monitoring:dashboard'): _('Public engagement'),
                   reverse('public_engagement_monitoring:user_events'): _('Events'),
                   reverse('public_engagement_monitoring:user_event', kwargs={'event_id': event_id}): event.title,
                   '#': _('General informations'),}
    form = PublicEngagementEventForm(request=request, instance=event)

    if not event.is_editable_by_user():
        messages.add_message(

kpi/unical_accounts/api/views.py
from django.contrib.auth import get_user_model
from django_filters.rest_framework import *

from rest_framework import filters, generics, permissions

from template.api.pagination import KpiPagination

from . serializers import *


class UserList(generics.ListAPIView):

    permission_classes = [permissions.IsAuthenticated]
    serializer_class = UserSerializer
    filter_backends = [DjangoFilterBackend,
                       filters.SearchFilter,
                       filters.OrderingFilter]
    search_fields = ['last_name','codice_fiscale']
    pagination_class = KpiPagination
    ordering = ['-last_name']
    queryset = get_user_model().objects.filter(is_active=True)


class UserDetail(generics.RetrieveAPIView):

    permission_classes = [permissions.IsAuthenticated]
    serializer_class = UserSerializer
    queryset = get_user_model().objects.filter(is_active=True)

kpi/unical_accounts/templates/account.html
{% extends "base_page.html" %}


{% load i18n %}
{% load static %}
{% load unical_accounts_tags %}


{% block top_content %}
<h2>{% trans "Account" %}</h2>
{% endblock top_content %}

{% block page_content %}
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th scope="row">{% trans "First name" %}</th>
            <td>{{ request.user.first_name|default:'-' }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Last name" %}</th>
            <td>{{ request.user.last_name|default:'-' }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Email" %}</th>
            <td>{{ request.user.email|default:'-' }}</td>
        </tr>
        <tr>
            <th scope="row">{% trans "Taxpayer ID" %}</th>
            <td>{{ request.user.codice_fiscale|default:'-' }}</td>
        </tr>
    </tbody>
</table>
{% accounts_settings_value "EDITABLE_FIELDS" as accounts_editable_fields %}
{% if accounts_editable_fields %}
<a href="{% url 'unical_accounts:change_data' %}" type="button" class="btn btn-success btn-block">
    {% trans "Edit" %}
</a>
{% endif %}
{% endblock page_content %}

kpi/unical_accounts/templates/change_user_data.html
{% extends "base_page.html" %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Edit user data" %}</h2>
{% endblock top_content %}

{% block page_content %}
{% include 'form_template.html' with form=form %}
{% endblock page_content %}

{% block extra_scripts %}
<!-- prevent submit form by press "enter" on field -->
<script>
document.querySelector ('form input').addEventListener ('keypress', function(e) {
    if(e.which == 13) {
        e.preventDefault();
        return false;
    }
});
document.querySelector ('form input').addEventListener ('keyup', function(e) {
    if(e.which == 13) {
        e.preventDefault();
        return false;
    }
});
</script>
{% endblock extra_scripts %}

kpi/unical_accounts/templates/edit_user.html
{% extends 'base_page.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Edit user" %}</h2>
{% endblock top_content %}

{% block top_buttons %}
<div class="pb-4 clearfix mt-5">
    <div class="float-lg-start d-inline">
        <a role="button"
           class="btn btn-outline-secondary"
           href="{% url 'unical_accounts:users' %}">
                <svg class="icon icon-xs">
                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
                </svg> {% trans "Users" %}
        </a>
    </div>
</div>
{% endblock top_buttons %}

{% block page_content %}
{% include 'form_template.html' with form=form %}
{% endblock page_content %}

kpi/unical_accounts/templates/new_user.html
{% extends 'base_page.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Add new user" %}</h2>
{% endblock top_content %}

{% block page_content %}
{% include 'form_template.html' with form=form %}
{% endblock page_content %}

kpi/unical_accounts/templates/users.html
{% extends 'base_page.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Users" %}</h2>
{% endblock top_content %}

{% block top_buttons %}
<div class="pb-4 clearfix mt-5">
    <div class="float-lg-end d-inline">
        <a role="button"
           class="btn btn-success"
           href="{% url 'unical_accounts:users-new' %}">
                <svg class="icon icon-xs icon-white">
                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-plus-circle"></use>
                </svg> {% trans "Add new user" %}
        </a>
    </div>
</div>
{% endblock top_buttons %}

{% block page_content %}
{% include 'datatables_users/table.html' %}
{% endblock page_content %}


{% block extra_scripts %}
    {% url 'unical_accounts:users' as var_url %}
    {% url 'unical_accounts:users_json' as ajax_url %}
    {% include 'datatables_users/datatable_script.html' with var_url=var_url ajax_url=ajax_url user_show_priority=user_show_priority %}
{% endblock extra_scripts %}



{% comment %}
{% block centered_container %}

<a role="button"
   class="btn btn-success float-right"
   href="{% url 'unical_accounts:users-new' %}">
        <svg class="icon icon-xs icon-white">
            <use xlink:href="{% static 'svg/sprites.svg' %}#it-plus-circle"></use>
        </svg> {% trans "Add new user" %}
</a>

{% if users %}
<div class="table-responsive">
    <table class="table table-sm table-hover table-striped">
        <thead>
            <tr>
                <th>{% trans "Surname" %}</th>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Tax code" %}</th>
                <th>{% trans "Email" %}</th>
                <th>{% trans "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.last_name }}</td>
                <td>{{ user.first_name }}</td>
                <td>{{ user.codice_fiscale }}</td>
                <td>{{ user.email }}</td>
                <td>
                    {% if user.created_by == request.user and not user.last_login %}
                        <a href="{% url 'unical_accounts:users-edit' user_tax_code=user.codice_fiscale %}">
                            <b>{% trans "Edit" %}</b>
                        </a>
                        <a href=""><b>{% trans "Delete" %}</b></a>
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
{% trans "No data" %}
{% endif %}

{% endblock centered_container %}
{% endcomment %}