kpi/kpi/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view


urlpatterns = [
    path(f'{settings.ADMIN_PATH}/', admin.site.urls),
    # path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # path('schema/', get_schema_view(title=API_TITLE)),
]

if 'detection_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('detection_management.urls',
                        namespace='detection')),

if 'visiting_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('visiting_management.urls',
                        namespace='visiting')),

if 'public_engagement_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('public_engagement_management.urls',
                        namespace='public_engagement')),

if 'template' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('template.urls', namespace='template')),

if 'unical_accounts' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('unical_accounts.urls',
                        namespace='unical_accounts')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    from djangosaml2 import views as saml2_views

    import saml2_sp.urls

    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

    urlpatterns += path('{}/login/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LoginView.as_view(), name='login'),
    urlpatterns += path('{}/acs/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.AssertionConsumerServiceView.as_view(), name='saml2_acs'),
    urlpatterns += path('{}/logout/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutInitView.as_view(), name='logout'),
    urlpatterns += path('{}/ls/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls'),
    urlpatterns += path('{}/ls/post/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls_post'),
    urlpatterns += path('{}/metadata/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.MetadataView.as_view(), name='saml2_metadata'),
else:
    urlpatterns += path('{}/login/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LoginView.as_view(
                            template_name='login.html'),
                        name='login'),
    urlpatterns += path('{}/logout/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LogoutView.as_view(
                            template_name='logout.html', next_page='/'),
                        name='logout'),

kpi/public_engagement_monitoring/urls.py
from django.urls import path

from . api.views import (generic as api_generic,
                         user as api_user,
                         operator as api_evaluation_operator,
                         patronage as api_patronage_operator,
                         manager as api_manager,
                         involved_personnel as api_involved_personnel,
                         involved_structures as api_involved_structures)

from . views import (generic,
                     involved_personnel,
                     involved_structures,
                     manager,
                     operator,
                     patronage,
                     user)


app_name = 'public_engagement_monitoring'


# app prefix
prefix = 'public-engagement-monitoring'

api_prefix = "api"
user_prefix = 'user'
involved_personnel_prefix = 'involved-personnel'
involved_structures_prefix = 'involved-structures'
operator_prefix = 'operator'
validator_prefix = 'evaluation'
patronage_prefix = 'patronage'
manager_prefix = 'manager'

urlpatterns = [
    path(f'{prefix}/', generic.dashboard, name='dashboard'),
    path(f'{prefix}/events/<int:event_id>/poster/download/', generic.download_event_poster, name='download_event_poster'),

    # user
    path(f'{prefix}/{user_prefix}/events/', user.events, name='user_events'),
    path(f'{prefix}/{user_prefix}/events/new/',
         user.new_event_choose_referent, name='user_new_event_choose_referent'),
    path(f'{prefix}/{user_prefix}/events/new/basic-info/',
         user.new_event_basic_info, name='user_new_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/',
         user.event, name='user_event'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/basic-info/',
         user.event_basic_info, name='user_event_basic_info'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/data/',
         user.event_data, name='user_event_data'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/report/',
         user.event_report, name='user_event_report'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/',
         user.event_people, name='user_event_people'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/people/delete/<int:person_id>/',
         user.event_people_delete, name='user_event_people_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/',
         user.event_structures, name='user_event_structures'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/structures/delete/<int:structure_id>/',
         user.event_structures_delete, name='user_event_structures_delete'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation/',
         user.event_request_evaluation, name='user_event_request_evaluation'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/request-evaluation-cancel/',
         user.event_request_evaluation_cancel, name='user_event_request_evaluation_cancel'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/clone/',
         user.event_clone, name='user_event_clone'),
    path(f'{prefix}/{user_prefix}/events/<int:event_id>/delete/',
         user.event_delete, name='user_event_delete'),

    # evaluation operator
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/',
         operator.dashboard, name='operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/',
         operator.events, name='operator_events'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/',
         operator.event, name='operator_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         operator.take_event, name='operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         operator.event_basic_info, name='operator_event_basic_info'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         operator.event_data, name='operator_event_data'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         operator.event_people, name='operator_event_people'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         operator.event_people_delete, name='operator_event_people_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         operator.event_structures, name='operator_event_structures'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         operator.event_structures_delete, name='operator_event_structures_delete'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         operator.event_evaluation, name='operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         operator.event_reopen_evaluation, name='operator_event_reopen_evaluation'),

    # patronage operator
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/',
         patronage.dashboard, name='patronage_operator_dashboard'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/',
         patronage.events, name='patronage_operator_events'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/',
         patronage.event, name='patronage_operator_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/take/',
         patronage.take_event, name='patronage_operator_take_event'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/evaluate/',
         patronage.event_evaluation, name='patronage_operator_event_evaluation'),
    path(f'{prefix}/{operator_prefix}/{patronage_prefix}/<str:structure_slug>/events/<int:event_id>/reopen-evaluation/',
         patronage.event_reopen_evaluation, name='patronage_operator_event_reopen_evaluation'),

    # involved structures
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/',
         involved_structures.dashboard, name='involved_structures_dashboard'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/',
        involved_structures.events, name='involved_structures_events'),
    path(f'{prefix}/{operator_prefix}/{involved_structures_prefix}/<str:structure_slug>/events/<int:event_id>/',
        involved_structures.event, name='involved_structures_event'),

    # manager
    path(f'{prefix}/{manager_prefix}/',
         manager.dashboard, name='manager_dashboard'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/',
         manager.events, name='manager_events'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/',
         manager.new_event_choose_referent, name='manager_new_event_choose_referent'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/new/basic-info/',
         manager.new_event_basic_info, name='manager_new_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/',
         manager.event, name='manager_event'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/basic-info/',
         manager.event_basic_info, name='manager_event_basic_info'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/data/',
         manager.event_data, name='manager_event_data'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/',
         manager.event_people, name='manager_event_people'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/people/delete/<int:person_id>/',
         manager.event_people_delete, name='manager_event_people_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/',
         manager.event_structures, name='manager_event_structures'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/structures/delete/<int:structure_id>/',
         manager.event_structures_delete, name='manager_event_structures_delete'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/report/',
         manager.event_report, name='manager_event_report'),
    path(f'{prefix}/{manager_prefix}/<str:structure_slug>/events/<int:event_id>/change-status/',
         manager.event_enable_disable, name='manager_event_enable_disable'),

    # involved personnel
    path(f'{prefix}/{involved_personnel_prefix}/events/', involved_personnel.events, name='involved_personnel_events'),
    path(f'{prefix}/{involved_personnel_prefix}/events/<int:event_id>/',
         involved_personnel.event, name='involved_personnel_event'),

    # API
    path(f'{prefix}/{api_prefix}/structures/', api_generic.OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/{api_prefix}/events/',
         api_generic.PublicEngagementApprovedEventList.as_view(), name='api_generic_approved_events'),
    path(f'{prefix}/{api_prefix}/events/<int:pk>/',
         api_generic.PublicEngagementApprovedEventDetail.as_view(), name='api_generic_approved_event'),
    path(f'{prefix}/{api_prefix}/{user_prefix}/events/',
         api_user.PublicEngagementEventList.as_view(), name='api_user_events'),
    path(f'{prefix}/{api_prefix}/{operator_prefix}/{validator_prefix}/<str:structure_slug>/events/',

kpi/template/urls.py
from django.urls import path
from .views import dashboard

app_name = 'template'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

kpi/unical_accounts/urls.py
from django.urls import path

from . datatables import *
from .views import *

app_name = "unical_accounts"

prefix = 'users'

urlpatterns = [

    # url(r'^login/$', Login, name='login'),
    # path('logout', Logout, name='logout'),

    path(f'{prefix}/users.json', datatables_users, name='users_json'),
    path(f'{prefix}/', users, name='users'),
    path(f'{prefix}/new/', new_user, name='users-new'),
    path(f'{prefix}/<str:user_tax_code>/edit/', edit_user, name='users-edit'),

    path('account/', account, name='account'),
    path('account/edit/', changeData, name='change_data'),
    path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),

]

kpi/visiting_management/urls.py
from django.urls import path

from . api.views import *
from . datatables import *
from . views import *


app_name = 'visiting'


# app prefix
prefix = 'visiting'

urlpatterns = [

    path(f'{prefix}/', dashboard, name='dashboard'),
    path(f'{prefix}/api/structures/', OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/api/structures/<int:pk>/', OrganizationalStructureDetail.as_view(), name='api_structure'),
    path(f'{prefix}/api/users/', VisitingUserList.as_view(), name='api_users'),
    path(f'{prefix}/api/users/<int:pk>/', VisitingUserDetail.as_view(), name='api_user'),

    # datatables
    path(f'{prefix}/<str:structure_slug>/visitings.json',
         datatables_structure_visitings, name='structure_visitings_json'),

    path(f'{prefix}/<str:structure_slug>/',
         structure_visitings, name='structure_visitings'),
    path(f'{prefix}/<str:structure_slug>/new/',
         new_structure_visiting, name='new_structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/',
         structure_visiting, name='structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/edit/',
         edit_structure_visiting, name='edit_structure_visiting'),
]

kpi/public_engagement_monitoring/api/views/generic.py
from django_filters.rest_framework import *

from organizational_area.api.views import *

from rest_framework import filters, generics, permissions

from template.api.pagination import KpiPagination

from ... utils import *
from .. filters import PublicEngagementEventFilter
from .. serializers import *


class PublicEngagementEventList(generics.ListAPIView):

    permission_classes = [permissions.IsAuthenticated]
    serializer_class = PublicEngagementEventSerializer
    filter_backends = [DjangoFilterBackend,
                       filters.SearchFilter,
                       filters.OrderingFilter]
    filterset_class =  PublicEngagementEventFilter
    search_fields = ['title', 'referent__last_name', 'structure__name']
    pagination_class = KpiPagination
    ordering_fields = ['start', 'end', 'title', 'referent__last_name']
    ordering = ['-start']


class PublicEngagementApprovedEventList(PublicEngagementEventList):
    serializer_class = PublicEngagementEventLiteSerializer

    def get_queryset(self, **kwargs):
        """
        """
        events = PublicEngagementEvent.objects\
            .prefetch_related('data', 'report')\
            .select_related('referent', 'structure')\
            .filter(structure__is_active=True,
                    operator_evaluation_success=True)

        return events


class PublicEngagementApprovedEventDetail(generics.RetrieveAPIView):
    serializer_class = PublicEngagementEventLiteSerializer
    queryset = PublicEngagementEvent.objects.all()


class OrganizationalStructureList(OrganizationalStructureList):
    permission_classes = [permissions.IsAuthenticated]
    queryset = OrganizationalStructure.objects.filter(is_active=True,
                                                      is_public_engagement_enabled=True,
                                                      is_internal=True,)

kpi/public_engagement_monitoring/api/views/involved_personnel.py
from django.db.models import Q


from rest_framework import permissions

from ... models import PublicEngagementEvent

# from .. permissions import *

from . generic import PublicEngagementEventList


class PublicEngagementEventList(PublicEngagementEventList):

    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self, **kwargs):
        """
        """
        events = PublicEngagementEvent.objects\
            .prefetch_related('data', 'report')\
            .select_related('referent', 'structure')\
            .filter(data__involved_personnel=self.request.user,
                    structure__is_active=True,
                    # ~ is_active=True,
                    operator_evaluation_date__isnull=False)
                    # ~ operator_evaluation_success=True)
        return events

kpi/public_engagement_monitoring/templates/pem/base.html
{% extends 'base_page.html' %}

{% load static %}


{% block header_center_logo %}
<div class="col-10 col-md-9 col-lg-12 offset-2 offset-md-0">
    <img src="{% static 'images/logo_unical_pe.jpg' %}" class="w-75"/>
</div>
{% endblock header_center_logo %}

kpi/public_engagement_monitoring/templates/pem/dashboard.html
{% extends 'pem/base.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "UniCal.PE platform" %}</h2>
<p>
    {% trans "In this section you can register and manage the Public Engagement initiatives of the University of Calabria." %}
</p>
{% endblock top_content %}

{% block clean_content %}
<hr class="my-5">
<p class="h5">
    <svg class="icon">
        <use href="{% static 'svg/sprites.svg' %}#it-tool"></use>
    </svg> {% trans "Management tools" %}
</p>
<div class="row mt-5">
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Event referent or his delegate' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'To register or modify an event' %}
                    </p>
                    <a class="read-more" href="{% url 'public_engagement_monitoring:user_events'%}">
                        <span class="text text-primary">{% trans "Manage" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Structure operator' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'To manager structure events' %}
                    </p>
                    <a class="read-more" href="{% url 'public_engagement_monitoring:operator_dashboard'%}">
                        <span class="text text-primary">{% trans "Evaluation" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                    <a class="read-more" style="left: 50%" href="{% url 'public_engagement_monitoring:patronage_operator_dashboard'%}">
                        <span class="text text-primary">{% trans "Patronage" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Manager' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'To manage all events' %}
                    </p>
                    <a class="read-more" href="{% url 'public_engagement_monitoring:manager_dashboard'%}">
                        <span class="text text-primary">{% trans "Manage" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
</div>
<hr class="my-5">
<p class="h5">
    <svg class="icon">
        <use href="{% static 'svg/sprites.svg' %}#it-password-visible"></use>
    </svg> {% trans "Read only access" %}
</p>
<div class="row mt-5">
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Other involved personnel' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'Access the data of the initiatives in which you have been included as "other involved personnel"' %}
                    </p>
                    <a class="read-more" href="{% url 'public_engagement_monitoring:involved_personnel_events'%}">
                        <span class="text text-primary">{% trans "Enter" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
    <div class="col-12 col-lg-4">
        <!--start card-->
        <div class="card-wrapper card-space">
            <div class="card card-bg">
                <div class="card-body">
                    <h5 class="card-title">
                        {% trans 'Other involved structures' %}
                    </h5>
                    <p class="card-text">
                        {% trans 'Access the data of the initiatives in which your structure has been involved' %}
                    </p>
                    <a class="read-more" href="{% url 'public_engagement_monitoring:involved_structures_dashboard'%}">
                        <span class="text text-primary">{% trans "Enter" %}</span>
                        <svg class="icon">
                            <use href="/static/svg/sprites.svg#it-arrow-right-circle"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
        <!--end card-->
    </div>
</div>
{% endblock clean_content %}

kpi/public_engagement_monitoring/templates/pem/event_basic_info.html
{% extends 'pem/base.html' %}}

{% load i18n %}
{% load static %}
{% load kpi_tags %}


{% block top_content %}
<h2>{% if event %}{{ event.title }}{% else %}Nuova iniziativa{% endif %}</h2>
<h3 style="font-weight: lighter">Informazioni generali</h3>

{% if request.session.referent %}
{% user_from_pk request.session.referent as referent %}
{% if referent %}
<div class="alert alert-info my-5" role="alert">
    <b>Referente scelto:</b> {{ referent }}
</div>
{% endif %}
{% endif %}
{% endblock top_content %}

{% block page_content %}
{% include "form_template.html" with form=form %}
{% endblock page_content %}

kpi/public_engagement_monitoring/templates/pem/event_data.html
{% extends 'pem/base.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{{ event.title }}</h2>
<h3 style="font-weight: lighter">Dati dell'iniziativa</h3>
{% endblock top_content %}

{% block page_content %}
{% include "form_template.html" with form=form %}
{% endblock page_content %}

kpi/public_engagement_monitoring/templates/pem/event_evaluation.html
{% extends 'pem/base.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{{ event.title }}</h2>
<h3 style="font-weight: lighter">{% trans "Evaluation" %}</h3>
{% endblock top_content %}

{% block page_content %}
{% include "form_template.html" with form=form %}
{% endblock page_content %}

kpi/public_engagement_monitoring/templates/pem/event_people.html
{% extends 'pem/base.html' %}

{% load i18n %}
{% load static %}
{% load public_engagement_monitoring_tags %}


{% block top_content %}
<h2>{{ event.title }}</h2>
<h3 style="font-weight: lighter">{% trans "Other involved personnel" %}</h3>
{% endblock top_content %}

{% block page_content %}
{% pem_settings_value "API_ADDRESSBOOK" as api_addressbook %}
<div id="addressbook">
    <div class="mt-3" v-if="person_id != ''">
        <div class="card-wrapper pb-0 mb-3">
            <div class="card no-after" style="border:1px solid #b71918">
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-12 align-left">
                            <span>
                                <b>[[ person_name ]]</b>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <form class="d-inline" method="post" noevaluate>
            <input type="hidden" name="person_id" :value="person_id" />
            {% csrf_token %}
            <button type="submit" class="btn btn-success">
                Conferma
            </button>
        </form>
        <button class="d-inline btn btn-danger ms-2" v-if="person_id != ''" @click="delete_selected_person()">
            Cancella
        </button>
    </div>
    <div v-else>
        <div class="row">
            <div class="col-12">
                <div class="card-wrapper card-space">
                    <div class="card card-bg no-after">
                        <div class="card-body">
                            <div class="row form-group">
                                <div class="col-md">
                                    <div class="input-group">
                                        <label for="search"></label>
                                        <input type="text"
                                               class="form-control"
                                               id="search"
                                               name="search"
                                               placeholder="{% trans 'Surname' %}"
                                               v-model="search_terms"
                                               v-on:keyup.enter="search()">
                                        <div class="input-group-append">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div v-if="is_loading">{% include "loader.html" %}</div>
        <div v-else>
            {% include "pagination.html" %}
            <div class="row w-100">
                <div class="col-12 col-md-6 mb-3" v-for="item in data.results">
                    <div class="card-wrapper pb-0">
                        <div class="card no-after" style="border:1px solid #b71918">
                            <div class="card-body p-3">
                                <div class="row">
                                    <div class="col-12 align-left">
                                        <span>
                                            <b>[[ item.Name ]]</b>
                                            <br>
                                            <div v-for="role in item.Roles">
                                                [[ role.RoleDescription ]]
                                                <br>
                                                [[ role.Structure ]]
                                            </div>
                                            <div v-for="email in item.Email">
                                                <span>
                                                    <svg class="icon icon-sm icon-muted me-2">
                                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-mail"></use>
                                                    </svg>
                                                    <a :href="'mailto:'+email">[[ email ]]</a>
                                                </span>
                                                <br>
                                            </div>
                                        </span>
                                        <span class="mt-3 btn btn-success" @click="set_person(item.ID, item.Name)">Seleziona</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include "pagination.html" %}
        </div>
    </div>
</div>
<script>
const app = Vue.createApp({
    delimiters: ['[[', ']]'],
    data () {
        return {
            data: [],
            is_loading: true,
            person_id: '',
            person_name: '',
            search_terms: '',
            url: '{{ api_addressbook }}',
            controller: null
        }
    },
    mounted () {
        this.getData()
    },
    methods: {
        set_person(id, name, surname) {
            this.person_id = id
            this.person_name = name
        },
        delete_selected_person() {
            this.person_id = ''
            this.person_name = ''
        },
        search() {
            this.controller.abort()
            this.getData(page=1);
        },
        getData(page=1, search=this.search_terms) {
            this.controller = new AbortController()
            let signal = this.controller.signal
            let url = this.url+'?page='+page
            if(search) url += '&search='+search
            this.is_loading = true
            axios
                .get(url, {signal})
                .then(
                    response => {
                        this.is_loading = false
                        this.data = response.data
                    }
                )
                .catch((error) => {});
        },
    },
}).mount('#addressbook')
</script>
{% endblock page_content %}