kpi/kpi/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

# from rest_framework.documentation import include_docs_urls
# from rest_framework.schemas import get_schema_view


urlpatterns = [
    path(f'{settings.ADMIN_PATH}/', admin.site.urls),
    # path('docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    # path('schema/', get_schema_view(title=API_TITLE)),
]

if 'detection_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('detection_management.urls',
                        namespace='detection')),

if 'visiting_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('visiting_management.urls',
                        namespace='visiting')),

if 'public_engagement_management' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('public_engagement_management.urls',
                        namespace='public_engagement')),

if 'template' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('template.urls', namespace='template')),

if 'unical_accounts' in settings.INSTALLED_APPS:
    urlpatterns += path('', include('unical_accounts.urls',
                        namespace='unical_accounts')),

if 'saml2_sp' in settings.INSTALLED_APPS:
    from djangosaml2 import views as saml2_views

    import saml2_sp.urls

    urlpatterns += path('', include((saml2_sp.urls, 'sp',))),

    urlpatterns += path('{}/login/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LoginView.as_view(), name='login'),
    urlpatterns += path('{}/acs/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.AssertionConsumerServiceView.as_view(), name='saml2_acs'),
    urlpatterns += path('{}/logout/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutInitView.as_view(), name='logout'),
    urlpatterns += path('{}/ls/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls'),
    urlpatterns += path('{}/ls/post/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.LogoutView.as_view(), name='saml2_ls_post'),
    urlpatterns += path('{}/metadata/'.format(settings.SAML2_URL_PREFIX),
                        saml2_views.MetadataView.as_view(), name='saml2_metadata'),
else:
    urlpatterns += path('{}/login/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LoginView.as_view(
                            template_name='login.html'),
                        name='login'),
    urlpatterns += path('{}/logout/'.format(settings.LOCAL_URL_PREFIX),
                        auth_views.LogoutView.as_view(
                            template_name='logout.html', next_page='/'),
                        name='logout'),

kpi/public_engagement_management/urls.py
from django.urls import path

from . datatables import *
from . views import *


app_name = 'public_engagement'


# app prefix
prefix = 'social-engagement'

urlpatterns = [

    path(f'{prefix}/', dashboard, name='dashboard'),
    path(f'{prefix}/info/', info, name='info'),

    # datatables
    path(f'{prefix}/<str:structure_slug>/public_engagements.json',
         datatables_structure_public_engagements, name='structure_public_engagements_json'),

    path(f'{prefix}/<str:structure_slug>/',
         structure_public_engagements, name='structure_public_engagements'),
    path(f'{prefix}/<str:structure_slug>/new/',
         structure_public_engagement_new, name='structure_public_engagement_new'),
    path(f'{prefix}/<str:structure_slug>/<str:public_engagement_pk>/',
         structure_public_engagement, name='structure_public_engagement'),
    path(f'{prefix}/<str:structure_slug>/<str:public_engagement_pk>/edit/',
         structure_public_engagement_edit, name='structure_public_engagement_edit'),
    path(f'{prefix}/<str:structure_slug>/<str:public_engagement_pk>/partners/add/',
         structure_public_engagement_partner_add, name='structure_public_engagement_partner_add'),
    path(f'{prefix}/<str:structure_slug>/<str:public_engagement_pk>/partners/<str:partner_pk>/edit/',
         structure_public_engagement_partner_edit, name='structure_public_engagement_partner_edit'),
    path(f'{prefix}/<str:structure_slug>/<str:public_engagement_pk>/partners/<str:partner_pk>/delete/',
         structure_public_engagement_partner_delete, name='structure_public_engagement_partner_delete'),
]

kpi/template/urls.py
from django.urls import path
from .views import dashboard

app_name = 'template'

urlpatterns = [
    path('', dashboard, name='dashboard'),
]

kpi/unical_accounts/urls.py
from django.urls import path

from . datatables import *
from .views import *

app_name = "unical_accounts"

prefix = 'users'

urlpatterns = [

    # url(r'^login/$', Login, name='login'),
    # path('logout', Logout, name='logout'),

    path(f'{prefix}/users.json', datatables_users, name='users_json'),
    path(f'{prefix}/', users, name='users'),
    path(f'{prefix}/new/', new_user, name='users-new'),
    path(f'{prefix}/<str:user_tax_code>/edit/', edit_user, name='users-edit'),

    path('account/', account, name='account'),
    path('account/edit/', changeData, name='change_data'),
    path('account/edit/confirm-email/', confirmEmail, name='confirm_email'),

]

kpi/visiting_management/urls.py
from django.urls import path

from . api.views import *
from . datatables import *
from . views import *


app_name = 'visiting'


# app prefix
prefix = 'visiting'

urlpatterns = [

    path(f'{prefix}/', dashboard, name='dashboard'),
    path(f'{prefix}/api/structures/', OrganizationalStructureList.as_view(), name='api_structures'),
    path(f'{prefix}/api/structures/<int:pk>/', OrganizationalStructureDetail.as_view(), name='api_structure'),
    path(f'{prefix}/api/users/', VisitingUserList.as_view(), name='api_users'),
    path(f'{prefix}/api/users/<int:pk>/', VisitingUserDetail.as_view(), name='api_user'),

    # datatables
    path(f'{prefix}/<str:structure_slug>/visitings.json',
         datatables_structure_visitings, name='structure_visitings_json'),

    path(f'{prefix}/<str:structure_slug>/',
         structure_visitings, name='structure_visitings'),
    path(f'{prefix}/<str:structure_slug>/new/',
         new_structure_visiting, name='new_structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/',
         structure_visiting, name='structure_visiting'),
    path(f'{prefix}/<str:structure_slug>/<str:visiting_pk>/edit/',
         edit_structure_visiting, name='edit_structure_visiting'),
]

kpi/public_engagement_management/views.py
import csv
import datetime

from django.contrib import messages
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from django.contrib.admin.utils import _get_changed_field_labels_from_form
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import gettext_lazy as _

# from organizational_area.decorators import belongs_to_an_office
from organizational_area.models import *

from template.utils import *

from . decorators import *
from . forms import *
from . models import *
from . settings import *


def _export_csv(data):
    # Create the HttpResponse object with the appropriate CSV header.
    name = f'social_engagement_{data["structure"]}_{data["year"]}.csv' if data['structure'] else f'social_engagement_{data["year"]}.csv'
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': f'attachment; filename="{name}"'},
    )

    writer = csv.writer(response, delimiter='$')
    entries = PublicEngagement.objects.filter(subscription_date__year=data['year'],
                                              is_active=True)\
                                      .order_by('subscription_date')
    if data['structure']:
        entries = entries.filter(structure=data['structure'])


    writer.writerow([_('Structure'),
                     _('Subject'),
                     _('Duration'),
                     _('Subscription date'),
                     _('Involves non-profit activity (No production of profit for the department)'),
                     _('Involves activities aimed at non-academic audiences (even outside the university campus)'),
                     _('Has a social value (meets one or more social objectives of the Agenda 2030 of ONU or pursues other social purposes)'),
                     _('Note'),
                     _('Partners'),
                     _('Partners number'),
                     _('Goals')])

    for e in entries:
        partners = PublicEngagementPartner.objects.filter(public_engagement=e).values_list('partner__name', flat=True)
        goals = PublicEngagementGoal.objects.filter(public_engagement=e).values_list('goal__name', flat=True)
        writer.writerow([e.structure,
                         e.subject,
                         e.duration,
                         e.subscription_date,
                         e.requirements_one,
                         e.requirements_two,
                         e.requirements_three,
                         e.note,
                         list(partners),
                         partners.count(),
                         list(goals)])
    return response


@transaction.atomic
def _save_public_engagement(structure, form, **kwargs):
    """
    Save public_engagement from form.
    Passing additional fields in kwargs.
    """
    public_engagement = form.save(commit=False)
    public_engagement.structure = structure

    # additional fields
    for k, v in kwargs.items():
        setattr(public_engagement, k, v)
        # update_fields.append(k)

    public_engagement.save()


    # set new goals
    PublicEngagementGoal.objects.filter(public_engagement=public_engagement).delete()
    goals = form.cleaned_data['goal']
    for goal in goals:
        PublicEngagementGoal.objects.create(public_engagement=public_engagement, goal=goal)

    return public_engagement


@transaction.atomic
def _save_public_engagement_partner(public_engagement, form, **kwargs):
    """
    Save public_engagement partner from form.
    Passing additional fields in kwargs.
    """
    public_engagement_partner = form.save(commit=False)
    public_engagement_partner.public_engagement = public_engagement

    # additional fields
    for k, v in kwargs.items():
        setattr(public_engagement_partner, k, v)
        # update_fields.append(k)

    public_engagement_partner.save()
    return public_engagement_partner


@login_required
# @belongs_to_an_office
def dashboard(request):

    is_manager = request.user.is_superuser or check_user_permission_on_model(request.user, PublicEngagement)

    template = 'dashboard_public_engagements.html'
    offices = check_user_permission_on_dashboard(request.user,
                                                 PublicEngagement,
                                                 PUBLIC_ENGAGEMENT_OFFICE_SLUG)
    if not offices:
        messages.add_message(request, messages.ERROR,
                             _("Permission denied"))
        return redirect('template:dashboard')

    form = PublicEngagementExportCSVForm()

    d = {'form': form,
         'my_offices': offices,
         'is_manager': is_manager}

    if is_manager:

        if request.POST:
            form = PublicEngagementExportCSVForm(data=request.POST)
            if form.is_valid():
                year = form.cleaned_data['year']
                structure = form.cleaned_data['structure']
                return _export_csv({'year': year, 'structure': structure})
            else:  # pragma: no cover
                for k, v in form.errors.items():
                    messages.add_message(request, messages.ERROR,
                                         f"<b>{form.fields[k].label}</b>: {v}")

        date_start = request.GET.get('date_start', None)
        date_end = request.GET.get('date_end', None)
        start = None
        end = None
        try:
            if date_start: start = datetime.datetime.strptime(date_start, "%Y-%m-%d").date()
            if date_end: end = datetime.datetime.strptime(date_end, "%Y-%m-%d").date()
        except:
            start = None
            end = None

        all_public_engagements = PublicEngagement.objects.filter(is_active=True)
        if start: all_public_engagements = all_public_engagements.filter(subscription_date__gte=start)
        if end: all_public_engagements = all_public_engagements.filter(subscription_date__lte=end)

        internal_str = OrganizationalStructure.objects\
                                              .filter(is_active=True,
                                                      is_internal=True)
        str_engagements = []
        for struct in internal_str:
            str_engagements.append(all_public_engagements.filter(structure=struct).count())


        goals_list = Goal.objects.filter(is_active=True)
        all_goals_results = PublicEngagementGoal.objects.filter(goal__is_active=True,
                                                                public_engagement__is_active=True)
        goals_results = []
        for goal in goals_list:
            if start: all_goals_results = all_goals_results.filter(public_engagement__subscription_date__gte=start)
            if end: all_goals_results = all_goals_results.filter(public_engagement__subscription_date__lte=end)
            goals_results.append(all_goals_results.filter(goal=goal).count())

        d.update({'date_start': date_start,
                  'date_end': date_end,
                  'goals_list': list(goals_list.values_list('name', flat=True)),
                  'goals_results': goals_results,
                  'internal_str': list(internal_str.values_list('name', flat=True)),
                  'str_engagements': str_engagements})

    return render(request, template, d)


@login_required
def info(request):
    offices = check_user_permission_on_dashboard(request.user,
                                                 PublicEngagement,
                                                 PUBLIC_ENGAGEMENT_OFFICE_SLUG)
    if not offices:
        messages.add_message(request, messages.ERROR,
                             _("Permission denied"))
        return redirect('template:dashboard')

    template = 'info_public_engagement.html'
    return render(request, template, {})


@login_required
@can_view_structure_public_engagements
def structure_public_engagements(request, structure_slug, structure=None):
    """
    param structure comes from @can_manage_structure_public_engagements
    """
    d = {'structure': structure}
    template = 'public_engagements.html'
    return render(request, template, d)


@login_required
@can_view_structure_public_engagements
def structure_public_engagement(request, structure_slug,
                                public_engagement_pk, structure=None):
    """
    param structure comes from @can_manage_structure_public_engagements
    """
    public_engagement = get_object_or_404(PublicEngagement,
                                          structure=structure,
                                          pk=public_engagement_pk)

    goals = PublicEngagementGoal.objects.filter(public_engagement=public_engagement)

    partners = PublicEngagementPartner.objects\
                                      .filter(public_engagement=public_engagement)\
                                      .select_related('partner')

    public_engagement_logs = LogEntry.objects.filter(content_type_id=ContentType.objects.get_for_model(public_engagement).pk,
                                                     object_id=public_engagement.pk)

    d = {'goals': goals,
         'partners': partners,
         'public_engagement_logs': public_engagement_logs,
         'public_engagement': public_engagement,
         'structure': structure}
    template = 'public_engagement.html'
    return render(request, template, d)


@login_required
@can_manage_structure_public_engagements
def structure_public_engagement_new(request, structure_slug, structure=None):
    """
    param structure comes from @can_manage_structure_public_engagements
    """
    form = PublicEngagementForm()
    if request.POST:
        form = PublicEngagementForm(request.POST)
        if form.is_valid():

            public_engagement = _save_public_engagement(form=form,

kpi/public_engagement_management/templates/public_engagement.html
{% extends 'base_page.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Social Engagement details" %}</h2>
<h4>{{ structure }} - {{ public_engagement.subject }}</h4>
{% endblock top_content %}

{% block top_buttons %}
<div class="pb-4 clearfix mt-5">
    <div class="float-lg-start d-inline">
        <a role="button" class="btn btn-outline-secondary" href="{% url 'public_engagement:dashboard' %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
            </svg> {% trans "Social Engagement management" %}
        </a>
    </div>
    <div class="float-lg-start d-inline">
        <a role="button" class="btn btn-outline-secondary" href="{% url 'public_engagement:structure_public_engagements' structure_slug=structure.slug %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
            </svg> {% trans "Back to" %} {{ structure }}
        </a>
    </div>

    <div class="float-lg-end d-inline">
        <a role="button"
           class="btn btn-outline-warning"
           href="{% url 'public_engagement:structure_public_engagement_edit' structure_slug=structure.slug public_engagement_pk=public_engagement.pk %}">
                <svg class="icon icon-xs">
                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
                </svg> {% trans "Edit" %}
        </a>
        <a role="button"
           class="btn btn-outline-success"
           href="{% url 'public_engagement:structure_public_engagement_partner_add' structure_slug=structure.slug public_engagement_pk=public_engagement.pk %}">
                <svg class="icon icon-xs">
                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-plus-circle"></use>
                </svg> {% trans "Add partner" %}
        </a>
    </div>
</div>
{% endblock top_buttons %}

{% block clean_content %}
<div class="row">
    <div class="col">
        <div class="card-space card-wrapper">
            <div class="card card-bg no-after">
                <div class="card-body">
                    <table class="table table-striped table-hover">
                        <tbody>
                            <tr>
                                <th scope="row">{% trans 'Enabled' %}</th>
                                <td>
                                    {% if public_engagement.is_active %}
                                    <svg class="icon icon-sm icon-success">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
                                    </svg>
                                     {% else %}
                                    <svg class="icon icon-sm icon-danger">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
                                    </svg>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans 'Subject of the Protocol' %}</th>
                                <td>{{ public_engagement.subject }}</td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans 'Subscription Date of the Protocol' %}</th>
                                <td>{{ public_engagement.subscription_date }}</td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans 'Duration (Months) of the Protocol' %}</th>
                                <td>{{ public_engagement.duration }}</td>
                            </tr>
                            {% if goals %}
                            <tr>
                                <th scope="row">{% trans 'Goals AGENDA ONU 2030' %}</th>
                                <td>
                                    <ul>
                                        {% for goal in goals %}
                                        <li>{{ goal.goal }}</li>
                                        {% endfor %}
                                    </ul>
                                </td>
                            </tr>
                            {% endif %}
                            <tr>
                                <th scope="row">{% trans 'Involves non-profit activity (No production of profit for the department)' %}</th>
                                <td>
                                    {% if public_engagement.requirements_one %}
                                    <svg class="icon icon-sm icon-success">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
                                    </svg>
                                     {% else %}
                                    <svg class="icon icon-sm icon-danger">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
                                    </svg>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans 'Involves activities aimed at non-academic audiences (even outside the university campus)' %}</th>
                                <td>
                                    {% if public_engagement.requirements_two %}
                                    <svg class="icon icon-sm icon-success">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
                                    </svg>
                                     {% else %}
                                    <svg class="icon icon-sm icon-danger">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
                                    </svg>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans 'Has a social value (meets one or more social objectives of the Agenda 2030 of ONU or pursues other social purposes)' %}</th>
                                <td>
                                    {% if public_engagement.requirements_three %}
                                    <svg class="icon icon-sm icon-success">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
                                    </svg>
                                     {% else %}
                                    <svg class="icon icon-sm icon-danger">
                                        <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
                                    </svg>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">{% trans 'Additional Notes of the Protocol' %}</th>
                                <td>{{ public_engagement.note|default:"-" }}</td>
                            </tr>
                        </tbody>
                    </table>
                    {% include "obj_logs.html" with logs=public_engagement_logs %}
                </div>
            </div>
        </div>
    </div>
</div>
{% if partners %}
<hr>
<h4>{% trans "Partner" %}</h4>
<div class="row">
    <div class="col">
        <div class="card-space card-wrapper">
            <div class="card card-bg no-after">
                <div class="card-body">
                    <table class="table table-striped table-hover">
                        <tbody>
                            <tr>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Is head" %}</th>
                                <th></th>
                            </tr>
                            {% for partner in partners %}
                            <tr>
                                <td>{{ partner.partner.name }}</td>
                                <td>
                                    {% if partner.is_head %}
                                        <svg class="icon icon-sm icon-success">
                                            <use xlink:href="{% static 'svg/sprites.svg' %}#it-check-circle"></use>
                                        </svg>
                                         {% else %}
                                        <svg class="icon icon-sm icon-danger">
                                            <use xlink:href="{% static 'svg/sprites.svg' %}#it-close-circle"></use>
                                        </svg>
                                        {% endif %}
                                </td>
                                <td class="text-right">
                                    <a href="{% url 'public_engagement:structure_public_engagement_partner_edit' structure_slug=structure.slug public_engagement_pk=public_engagement.pk partner_pk=partner.pk %}" class="btn btn-primary btn-xs">
                                        <svg class="icon icon-xs icon-white">
                                            <use xlink:href="{% static 'svg/sprites.svg' %}#it-pencil"></use>
                                        </svg> {% trans "Edit" %}
                                    </a>
                                    <a href="" class="btn btn-danger btn-xs"
                                       data-toggle="modal"
                                       data-target="#delete_partner_{{ partner.pk }}">
                                        <svg class="icon icon-xs icon-white">
                                            <use xlink:href="{% static 'svg/sprites.svg' %}#it-delete"></use>
                                        </svg> {% trans "Remove" %}
                                    </a>
                                    <div class="modal fade"
                                         tabindex="-1"
                                         role="dialog"
                                         id="delete_partner_{{ partner.pk }}">
                                        <div class="modal-dialog modal-dialog-centered"
                                             role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">
                                                        {% trans "Confirm" %}
                                                    </h5>
                                                    <button class="close"
                                                            type="button"
                                                            data-dismiss="modal"
                                                            aria-label="Close">
                                                       <svg class="icon">
                                                          <use xlink:href="{% static 'svg/sprites.svg' %}#it-close"></use>
                                                       </svg>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        {% trans "Do you want to delete choosen partner?" %}
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <a class="btn btn-success btn-sm" href="{% url 'public_engagement:structure_public_engagement_partner_delete' structure_slug=structure.slug public_engagement_pk=public_engagement.pk partner_pk=partner.pk %}">
                                                        {% trans 'Yes, proceed' %}
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock clean_content %}

kpi/public_engagement_management/templates/public_engagements.html
{% extends 'base_page.html' %}

{% load i18n %}
{% load static %}


{% block top_content %}
<h2>{% trans "Social Engagement" %}</h2>
<h4>{{ structure }}</h4>
{% endblock top_content %}

{% block top_buttons %}
<div class="pb-4 clearfix mt-5">
    <div class="float-lg-start d-inline">
        <a role="button" class="btn btn-outline-secondary" href="{% url 'public_engagement:dashboard' %}">
            <svg class="icon icon-xs">
                <use xlink:href="{% static 'svg/sprites.svg' %}#it-arrow-left"></use>
            </svg> {% trans "Social Engagement management" %}
        </a>
    </div>

    <div class="float-lg-end d-inline">
        <a role="button"
           class="btn btn-outline-success"
           href="{% url 'public_engagement:structure_public_engagement_new' structure_slug=structure.slug %}">
                <svg class="icon icon-xs">
                    <use xlink:href="{% static 'svg/sprites.svg' %}#it-plus-circle"></use>
                </svg> {% trans "Add new" %}
        </a>
    </div>
</div>
{% endblock top_buttons %}

{% block page_content %}
{% include 'datatables_public_engagement/table.html' %}
{% endblock page_content %}


{% block extra_scripts %}
    {% url 'public_engagement:structure_public_engagements' structure_slug=structure.slug as var_url %}
    {% url 'public_engagement:structure_public_engagements_json' structure_slug=structure.slug as ajax_url %}
    {% include 'datatables_public_engagement/datatable_script.html' with var_url=var_url ajax_url=ajax_url user_show_priority=user_show_priority %}
{% endblock extra_scripts %}